// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gdogdsvxiagsnceoqhhh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdkb2dkc3Z4aWFnc25jZW9xaGhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NTA3MjgsImV4cCI6MjA2MTQyNjcyOH0.P2h5oGVMU6N4PbReQRZizyj2YeGBMh9XmV7iqMrBWk8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);